### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by raazmi** [pankajladhar/GFontsSpace#2]
Please add line-height option to this playground. I think this gets a boost with line-height option.

**Comment by pankajladhar** [comment]
Could you please elobrare bit more about this requirement ??

**Comment by pankajladhar** [comment]
Sorry for late reply I was bit busy with project work

**Comment by pankajladhar** [comment]
Feature is done. As part of https://github.com/pankajladhar/GFontsSpace/pull/4
